#!/usr/bin/env python3
"""Assemble slides.tex from outline.yaml.

Walks frames in order, emitting \\section / \\subsection on change and
\\input{frames/<id>.tex} for each frame. Title/author/theme come from `deck`.
Idempotent: re-run after typesetting frames to (re)build the merged deck.

    uv run --with pyyaml python tools/gen-slides.py
"""
import sys, pathlib, yaml

REPO = pathlib.Path(__file__).resolve().parent.parent
outline = yaml.safe_load((REPO / "outline.yaml").read_text(encoding="utf-8"))
deck = outline["deck"]
frames = outline["frames"]

title = deck["title"]
subtitle = ""
# A title like "A——B" reads better split into title + subtitle on the title page.
for sep in ("——", "—"):
    if sep in title:
        title, subtitle = (p.strip() for p in title.split(sep, 1))
        break

short_title = deck.get("short_title", title)
author = deck["author"]
theme = deck.get("theme", "villa")
template = deck.get("template", "full")
theme_opt = "[nosection]" if template == "short" else ""
if theme in ("uestc", "pku"):
    theme_opt = ("[%s,%s]" % (theme, "nosection") if template == "short" else "[%s]" % theme)

out = []
w = out.append
w("% AUTO-GENERATED by tools/gen-slides.py from outline.yaml — do not hand-edit;")
w("% edit outline.yaml + frames/<id>.tex, then regenerate.")
w("\\documentclass[aspectratio=169]{ctexbeamer}")
w("\\input{preamble.tex}")
w("\\usetheme%s{villa}" % theme_opt)
w("")
w("\\title[%s]{%s}" % (short_title, title))
if subtitle:
    w("\\subtitle{%s}" % subtitle)
w("\\author[%s]{%s}" % (author, author))
w("\\date[\\today]{\\today}")
w("")
if template != "short":
    w("% 每个 section 前插入高亮当前节的目录页（villa full 模版习惯）")
    w("\\AtBeginSection[]{\\begin{frame}<beamer>\\frametitle{目录}\\tableofcontents[currentsection]\\end{frame}}")
w("")
w("\\begin{document}")
w("")
w("\\begin{frame}[plain,noframenumbering]\\titlepage\\end{frame}")
if template != "short":
    w("")
    w("\\begin{frame}{目录}\\tableofcontents\\end{frame}")
w("")

cur_sec = cur_sub = None
for fr in frames:
    sec = fr.get("section")
    sub = fr.get("subsection")
    if template != "short" and sec and sec != cur_sec:
        w("")
        w("\\section{%s}" % sec)
        cur_sec = sec
        cur_sub = None
    if template != "short" and sub and sub != cur_sub:
        w("\\subsection{%s}" % sub)
        cur_sub = sub
    w("\\input{frames/%s.tex}" % fr["id"])

w("")
w("\\end{document}")

(REPO / "slides.tex").write_text("\n".join(out) + "\n", encoding="utf-8")
print("wrote slides.tex  (%d frames, theme=%s%s)" % (len(frames), theme, theme_opt))
